### ISSUE TITLE
log lines only shown in 4096 byte intervals

### ISSUE THREAD

**Issue by cweiske** [coderanger/supervisor-stdout#10]
When using `supervisor-stdout`, "docker run" only shows the log lines in 4096 byte intervals.
Only when at least 4096 bytes got logged by the programs, they are output/sent to docker.
The rest of the data is held back/buffered until the next 4096 byte block is full.

Is there a way to configure this? It's hindering me whilst debugging.

My programs had the following supervisor configuration:
```
[eventlistener:stdout]
command = supervisor_stdout
buffer_size = 100
events = PROCESS_LOG
result_handler = supervisor_stdout:event_handler

[program:lalala]
stdout_events_enabled=true
stderr_events_enabled=true
stdout_logfile_maxbytes = 1MB
stdout_logfile_backups = 0
stderr_logfile_maxbytes = 1MB
stderr_logfile_backups = 0
```

----

When not using supervisor-stdout but simply `stdout_logfile=/dev/stdout / redirect_stderr=true / stdout_logfile_maxbytes=0` it works without delay.

----

When starting bash in the docker container, and then manually starting supervisord, the output is immediate.

So I guess it's an issue with docker itself.

**Comment by cweiske** [comment]
I once had this issue when piping a program's output several times; http://cweiske.de/tagebuch/linux-speak-chatlogs.htm#p5 - pipe buffering that can be modified on cli with `stdbuf`. I guess that's going on here, tool

**Comment by coderanger** [comment]
Try changing the `print` to use `write_stdout`? If that doesn't work, I'm not sure where else there would be a buffer I control.

**Comment by cweiske** [comment]
Changing that did not make a difference.

But I modified the `supervisord` command so that it runs [`python -u`](https://python.readthedocs.io/en/v2.7.2/using/cmdline.html#cmdoption-u) instead of `python` - and then it works; the log lines come out immediately.

**Comment by coderanger** [comment]
:+1: If there is a way to force stdout to be unbuffered within Python I'm happy to do that.

**Comment by cweiske** [comment]
I don't have enough python knowledge to get to the bottom of the issue and am satisfied with the environment variable, so I'll close it now.
