### ISSUE TITLE
Difference to `stdout_logfile=/dev/stdout`?

### ISSUE THREAD

**Issue by cweiske** [coderanger/supervisor-stdout#9]
In http://stackoverflow.com/q/31174151/282601 someone simply uses `stdout_logfile=/dev/stdout` to push the output of programs to the supervisor output.

How is `supervisor-stdout` different to that?

----

Example from the link above:
```
[supervisord]
logfile=/dev/null
nodaemon=true

[program:autofs]
command=automount -f
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:split-pdf]
command=bin/split-pdf-server
directory=/root/split-pdf
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
```

**Comment by coderanger** [comment]
This prefixes each line so you know _which_ process a given line came from.

**Comment by cweiske** [comment]
The prefix was a relatively late addition (2016), while the initial `supervisor-stdout` code is from 2012.

Surely there must have been something else?

**Comment by coderanger** [comment]
It always did a prefix, the PR a few months ago was to fix the output for multi-line log messages.

**Comment by cweiske** [comment]
oh, ok. thanks.
